### ISSUE TITLE
Requesting access on the repo

### ISSUE THREAD

**Issue by sonia1goyal** [JPHaus/data-engineering-wiki#1]
Hi @JPHaus ,
I am new to github and open source. I was checking your repo and wanted to contribute in it. Could you please grant me access on it?

**Comment by JPHaus** [comment]
Hey @sonia1goyal!

Check out the instructions under [CONTRIBUTING.md](https://github.com/JPHaus/data-engineering-wiki/blob/main/CONTRIBUTING.md) on how to contribute to this repo and open another ticket if you have any questions.
